esphome:
  name: basic-vesc
  friendly_name: basic-vesc

esp32:
  board: lolin32_lite
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: components
    components: [vesc_component, ble_uart_component]

uart:
  id: esp_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

vesc_component:
  id: my_vesc_hub
  uart: esp_uart
  update_interval: 2s
  motor_pole_pairs: 21
  boost_interval: 150
  boost_duration: 3000

sensor:
  - platform: vesc_component
    vesc_id: my_vesc_hub
    voltage:
      name: "Supply Voltage"
    speed:
      name: "Speed"
    power:
      name: "Power"
    fet_temp:
      name: "VESC Temperature"

number:
  - platform: vesc_component
    vesc_id: my_vesc_hub
    speed_control:
      name: "Target Speed"
      min_value: 0
      max_value: 410
      step: 1

# Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:
