esphome:
  name: ceiling-fan
  friendly_name: ceiling_fan
  includes:
  libraries:
  on_boot:
    #priority: 200
    then:
      - lambda: "id(my_vesc_ptr) = id(my_vesc_hub);"
  #platformio_options:
  #  build_flags:
  #    - -DUSE_NIMBLE
  #    - -DCONFIG_BT_ENABLED=1
  #    - -DCONFIG_BT_NIMBLE_ENABLED=1
  #    - -DCONFIG_BT_CONTROLLER_ENABLED=1

esp32:
  board: lolin32_lite
  framework:
    type: arduino

logger:
  # Log levels (least → most noisy):
  # NONE → ERROR → WARN → INFO → DEBUG → VERBOSE → VERY_VERBOSE
  level: DEBUG
  logs:
    #vesc: DEBUG
    #ble_uart: DEBUG
    sensor: WARN
    number: WARN
    #text_sensor: WARN
    #api.service: WARN
  baud_rate: 0 #disabled
  #baud_rate: 115200

external_components:
  - source:
      type: local
      path: components
    components: [vesc_component, ble_uart_component]

# Sensors

sensor:
  - platform: vesc_component
    vesc_id: my_vesc_hub
    voltage:
      name: "Input Voltage"
      id: vesc_voltage
      filters:
        - delta: 0.1
    rpm:
      name: "RPM"
      id: vesc_rpm
      #filters:
      #  - delta: 1.0
    duty:
      name: "Duty Cycle"
      id: vesc_duty
      filters:
        - delta: 0.005
    input_current:
      name: "Input Current"
      id: vesc_input_current
      filters:
        - delta: 0.005
    phase_current:
      name: "Phase Current"
      id: vesc_phase_current
      filters:
        - delta: 0.03
    fet_temp:
      name: "FET Temperature"
      id: vesc_fet_temp
      filters:
        - delta: 0.2
    wattage:
      name: "Power"
      id: vesc_wattage
      filters:
        - delta: 0.005
    fault_code:
      name: "Fault Code"
      id: vesc_fault_code
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

text_sensor:
  - platform: vesc_component
    vesc_id: my_vesc_hub
    control_mode:
      name: "Control Mode"
      id: vesc_control_mode
    fault_text:
      name: "Fault Code"
    lisp_print:
      name: "Lisp Output"

# Controls

number:
  - platform: vesc_component
    vesc_id: my_vesc_hub
    rpm_control:
      name: "Motor Target RPM"
      id: rpm_slider
      min_value: -100
      max_value: 410
      step: 1
      unit_of_measurement: "RPM"
      mode: SLIDER
    current_control:
      name: "Motor Target Current"
      id: current_slider
      min_value: 0
      max_value: 2.8
      step: 0.028
      unit_of_measurement: "A"
      mode: SLIDER
    duty_control:
      name: "Motor Target Duty Cycle"
      id: duty_slider
      min_value: 0
      max_value: 0.5
      step: 0.005
      unit_of_measurement: "%"
      mode: SLIDER

switch:
  - platform: template
    id: ble_bridge_enabled
    name: "BLE UART Bridge"
    icon: "mdi:bluetooth"
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      return id(my_ble_uart_component).is_enabled();
    turn_on_action:
      lambda: id(my_ble_uart_component).set_enabled(true);
    turn_off_action:
      lambda: id(my_ble_uart_component).set_enabled(false);

button:
  - platform: template
    id: stop
    name: "Stop"
    icon: "md:cancel"
    on_press:
      - lambda: |-
          id(my_vesc_hub).stop();
  - platform: template
    id: reboot
    name: "Reboot"
    icon: "md:recycle"
    on_press:
      - lambda: |-
          id(my_vesc_hub).rebootVesc();
          id(my_vesc_hub).reboot();

uart:
  id: esp_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200
#debug:
#  direction: BOTH
#  dummy_receiver: false

# Optional debug UART (uncomment if you want a separate debug port)
# uart:
#   - id: debug_uart
#     tx_pin: 1
#     rx_pin: 3
#     baud_rate: 115200

vesc_component:
  id: my_vesc_hub
  update_interval: 2s
  uart: esp_uart
  ble_uart_component_id: my_ble_uart_component
  #debug_port: debug_uart
  motor_pole_pairs: 21 # Used for RPM <-> eRPM conversion
  boost_interval: 150 # Frequency of telemetry updates after a control input (ms) (0 to disable)
  boost_duration: 3000 # Duration of the snappy telemetry (ms) (0 to disable)

# Define the global variable to store our custom component instance
globals:
  - id: my_vesc_ptr
    # Use the full namespace and the class name
    type: esphome::vesc_component::VescComponent*
    initial_value: "nullptr"

ble_uart_component:
  id: my_ble_uart_component
  uart_id: esp_uart # share the VESC UART bus
  device_name: "Ceiling Fan" # advertised name

# Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:
