esphome:
  name: ceiling-fan
  friendly_name: ceiling_fan
  includes:
  libraries:
    # - ESP32 BLE Arduino
  on_boot:
    #priority: 200
    then:
      - lambda: "id(my_vesc_ptr) = id(my_vesc_hub);"

esp32:
  board: lolin32_lite
  framework:
    type: arduino

esp32_ble:

# The linker will fail if this is missing
# TODO Find a better way to handle this than having a dummy component in the config
# esp32_ble_tracker:

# Enable logging
logger:
  # Log levels (least → most noisy):
  # NONE → ERROR → WARN → INFO → DEBUG → VERBOSE → VERY_VERBOSE
  level: DEBUG
  #logs:
  #vesc: DEBUG
  #ble_uart: DEBUG
  #sensor: WARN
  #number: WARN
  #esp32_ble: WARN
  #api.service: WARN
  baud_rate: 0

external_components:
  - source:
      type: local
      path: components
    components: [vesc_component, ble_uart_component]

# Sensors

sensor:
  - platform: vesc_component
    vesc_id: my_vesc_hub
    voltage:
      name: "Input Voltage"
      id: vesc_voltage
    rpm:
      name: "RPM"
      id: vesc_rpm
    duty_cycle:
      name: "Duty Cycle"
      id: vesc_duty_cycle
    input_current:
      name: "Input Current"
      id: vesc_input_current
    phase_current:
      name: "Phase Current"
      id: vesc_phase_current
    fet_temp:
      name: "FET Temperature"
      id: vesc_fet_temp
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

# Controls

number:
  - platform: vesc_component
    vesc_id: my_vesc_hub
    rpm_control:
      name: "Motor Target RPM"
      id: rpm_slider
      unit_of_measurement: "RPM"
      mode: SLIDER
    current_control:
      name: "Motor Target Current"
      id: current_slider
      unit_of_measurement: "A"
      mode: SLIDER
    duty_cycle_control:
      name: "Motor Target Duty Cycle"
      id: duty_cycle_slider
      unit_of_measurement: "%"
      mode: SLIDER

switch:
  - platform: template
    id: ble_bridge_enabled
    name: "BLE Bridge Enabled"
    icon: "mdi:bluetooth"
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      return id(my_ble_uart_component).is_enabled();
    turn_on_action:
      lambda: id(my_ble_uart_component).set_enabled(true);
    turn_off_action:
      lambda: id(my_ble_uart_component).set_enabled(false);

button:
  - platform: restart
    id: reboot
    name: "Reboot"

uart:
  id: esp_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200
#debug:
#  direction: BOTH
#  dummy_receiver: false

# Optional debug UART (uncomment if you want a separate debug port)
# uart:
#   - id: debug_uart
#     tx_pin: 1
#     rx_pin: 3
#     baud_rate: 115200

vesc_component:
  id: my_vesc_hub
  update_interval: 2s
  uart: esp_uart
  ble_uart_component_id: my_ble_uart_component
  #debug_port: debug_uart

# Define the global variable to store our custom component instance
globals:
  - id: my_vesc_ptr
    # Use the full namespace and the class name
    type: esphome::vesc_component::VescComponent*
    initial_value: "nullptr"

ble_uart_component:
  id: my_ble_uart_component
  uart_id: esp_uart # share the VESC UART bus
  device_name: "Ceiling Fan" # advertised name

# Enable Home Assistant API
api:
  encryption:
    key: "+yVKF7n3gKxupWNXsMz05HtMTbSaohGJO+usOoCLyLQ="

ota:
  - platform: esphome
    password: "67ea0784bdf4766ea7f020ff7939d8c1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:
